# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    parameter_name:
#YAUM\Contract\UserService
#YAUM\Service\UserServiceDefault
services:
#    service_name:
#        class: YAUMSymfonyBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    user_service.default:
        class: YAUM\Service\UserServiceDefault
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    user_service:
        alias: user_service.default

    default_controller:
        class: YAUMSymfonyBundle\Controller\DefaultController
        arguments: ["@user_service"]

<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:framework="http://symfony.com/schema/dic/symfony"
    xsi:schemaLocation="http://symfony.com/schema/dic/services
        http://symfony.com/schema/dic/services/services-1.0.xsd
        http://symfony.com/schema/dic/symfony
        http://symfony.com/schema/dic/symfony/symfony-1.0.xsd">

      <services>
          <service id="app.hello_controller" class="YAUMSymfonyBundle\Controller\HelloController" />
      </services>

</container>